[package]
name                   = "atomiks"
description            = "typed atomics for any value that fits one atomic word."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
authors.workspace      = true
repository.workspace   = true

[lints]
workspace = true

[features]
default = []
loom    = ["dep:loom", "dep:tracing", "dep:tracing-subscriber"]

[target.'cfg(loom)'.dependencies]
# external
loom               = { workspace = true, optional = true }
tracing            = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

[dev-dependencies]
# external
proptest = { workspace = true }
trybuild = { workspace = true }
