[package]
name    = "atomiks-core-codegen"
version = "0.0.0"
edition = "2024"
publish = false

[features]
default         = []
aarch64-only    = []
aarch64-refused = []

[dependencies]
# external
deranged = { version = "0.5.8", default-features = false }
# internal
atomiks-core = { path = "../..", features = ["deranged-05"] }

[workspace]
